image: archlinux
packages:
  - nodejs-n
  - yarn
sources:
  - https://git.sr.ht/~statianzo/angularjs-testing-library
tasks:
  - setup: |
      sudo n stable
      cd angularjs-testing-library
      yarn
  - validate: |
      cd angularjs-testing-library
      yarn validate
  - publish: |
      cd angularjs-testing-library
      yarn run travis-after-success
