image: archlinux
packages:
  - nodejs-n
  - yarn
sources:
  - https://git.sr.ht/~statianzo/angularjs-testing-library
secrets:
  - 01f84277-3abe-4ed1-9d0d-d66b49bfcfe7
  - 5756e542-1a3e-4c27-ac4c-4820cff2b965
  - 576364b7-4764-4794-a536-1a3357fb222b
tasks:
  - setup: |
      sudo n stable
      cd angularjs-testing-library
      yarn
  - validate: |
      cd angularjs-testing-library
      yarn validate
  - publish: |
      . ~/.npm-token
      cd angularjs-testing-library
      CI=true yarn semantic-release
